require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MacroprocesosController do

  # This should return the minimal set of attributes required to create a valid
  # Macroproceso. As you add validations to Macroproceso, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MacroprocesosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all macroprocesos as @macroprocesos" do
      macroproceso = Macroproceso.create! valid_attributes
      get :index, {}, valid_session
      assigns(:macroprocesos).should eq([macroproceso])
    end
  end

  describe "GET show" do
    it "assigns the requested macroproceso as @macroproceso" do
      macroproceso = Macroproceso.create! valid_attributes
      get :show, {:id => macroproceso.to_param}, valid_session
      assigns(:macroproceso).should eq(macroproceso)
    end
  end

  describe "GET new" do
    it "assigns a new macroproceso as @macroproceso" do
      get :new, {}, valid_session
      assigns(:macroproceso).should be_a_new(Macroproceso)
    end
  end

  describe "GET edit" do
    it "assigns the requested macroproceso as @macroproceso" do
      macroproceso = Macroproceso.create! valid_attributes
      get :edit, {:id => macroproceso.to_param}, valid_session
      assigns(:macroproceso).should eq(macroproceso)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Macroproceso" do
        expect {
          post :create, {:macroproceso => valid_attributes}, valid_session
        }.to change(Macroproceso, :count).by(1)
      end

      it "assigns a newly created macroproceso as @macroproceso" do
        post :create, {:macroproceso => valid_attributes}, valid_session
        assigns(:macroproceso).should be_a(Macroproceso)
        assigns(:macroproceso).should be_persisted
      end

      it "redirects to the created macroproceso" do
        post :create, {:macroproceso => valid_attributes}, valid_session
        response.should redirect_to(Macroproceso.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved macroproceso as @macroproceso" do
        # Trigger the behavior that occurs when invalid params are submitted
        Macroproceso.any_instance.stub(:save).and_return(false)
        post :create, {:macroproceso => {}}, valid_session
        assigns(:macroproceso).should be_a_new(Macroproceso)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Macroproceso.any_instance.stub(:save).and_return(false)
        post :create, {:macroproceso => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested macroproceso" do
        macroproceso = Macroproceso.create! valid_attributes
        # Assuming there are no other macroprocesos in the database, this
        # specifies that the Macroproceso created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Macroproceso.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => macroproceso.to_param, :macroproceso => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested macroproceso as @macroproceso" do
        macroproceso = Macroproceso.create! valid_attributes
        put :update, {:id => macroproceso.to_param, :macroproceso => valid_attributes}, valid_session
        assigns(:macroproceso).should eq(macroproceso)
      end

      it "redirects to the macroproceso" do
        macroproceso = Macroproceso.create! valid_attributes
        put :update, {:id => macroproceso.to_param, :macroproceso => valid_attributes}, valid_session
        response.should redirect_to(macroproceso)
      end
    end

    describe "with invalid params" do
      it "assigns the macroproceso as @macroproceso" do
        macroproceso = Macroproceso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Macroproceso.any_instance.stub(:save).and_return(false)
        put :update, {:id => macroproceso.to_param, :macroproceso => {}}, valid_session
        assigns(:macroproceso).should eq(macroproceso)
      end

      it "re-renders the 'edit' template" do
        macroproceso = Macroproceso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Macroproceso.any_instance.stub(:save).and_return(false)
        put :update, {:id => macroproceso.to_param, :macroproceso => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested macroproceso" do
      macroproceso = Macroproceso.create! valid_attributes
      expect {
        delete :destroy, {:id => macroproceso.to_param}, valid_session
      }.to change(Macroproceso, :count).by(-1)
    end

    it "redirects to the macroprocesos list" do
      macroproceso = Macroproceso.create! valid_attributes
      delete :destroy, {:id => macroproceso.to_param}, valid_session
      response.should redirect_to(macroprocesos_url)
    end
  end

end
