require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrganismosInternosController do

  # This should return the minimal set of attributes required to create a valid
  # OrganismoInterno. As you add validations to OrganismoInterno, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrganismosInternosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all organismos_internos as @organismos_internos" do
      organismo_interno = OrganismoInterno.create! valid_attributes
      get :index, {}, valid_session
      assigns(:organismos_internos).should eq([organismo_interno])
    end
  end

  describe "GET show" do
    it "assigns the requested organismo_interno as @organismo_interno" do
      organismo_interno = OrganismoInterno.create! valid_attributes
      get :show, {:id => organismo_interno.to_param}, valid_session
      assigns(:organismo_interno).should eq(organismo_interno)
    end
  end

  describe "GET new" do
    it "assigns a new organismo_interno as @organismo_interno" do
      get :new, {}, valid_session
      assigns(:organismo_interno).should be_a_new(OrganismoInterno)
    end
  end

  describe "GET edit" do
    it "assigns the requested organismo_interno as @organismo_interno" do
      organismo_interno = OrganismoInterno.create! valid_attributes
      get :edit, {:id => organismo_interno.to_param}, valid_session
      assigns(:organismo_interno).should eq(organismo_interno)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrganismoInterno" do
        expect {
          post :create, {:organismo_interno => valid_attributes}, valid_session
        }.to change(OrganismoInterno, :count).by(1)
      end

      it "assigns a newly created organismo_interno as @organismo_interno" do
        post :create, {:organismo_interno => valid_attributes}, valid_session
        assigns(:organismo_interno).should be_a(OrganismoInterno)
        assigns(:organismo_interno).should be_persisted
      end

      it "redirects to the created organismo_interno" do
        post :create, {:organismo_interno => valid_attributes}, valid_session
        response.should redirect_to(OrganismoInterno.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved organismo_interno as @organismo_interno" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismoInterno.any_instance.stub(:save).and_return(false)
        post :create, {:organismo_interno => {}}, valid_session
        assigns(:organismo_interno).should be_a_new(OrganismoInterno)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismoInterno.any_instance.stub(:save).and_return(false)
        post :create, {:organismo_interno => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested organismo_interno" do
        organismo_interno = OrganismoInterno.create! valid_attributes
        # Assuming there are no other organismos_internos in the database, this
        # specifies that the OrganismoInterno created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrganismoInterno.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => organismo_interno.to_param, :organismo_interno => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested organismo_interno as @organismo_interno" do
        organismo_interno = OrganismoInterno.create! valid_attributes
        put :update, {:id => organismo_interno.to_param, :organismo_interno => valid_attributes}, valid_session
        assigns(:organismo_interno).should eq(organismo_interno)
      end

      it "redirects to the organismo_interno" do
        organismo_interno = OrganismoInterno.create! valid_attributes
        put :update, {:id => organismo_interno.to_param, :organismo_interno => valid_attributes}, valid_session
        response.should redirect_to(organismo_interno)
      end
    end

    describe "with invalid params" do
      it "assigns the organismo_interno as @organismo_interno" do
        organismo_interno = OrganismoInterno.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismoInterno.any_instance.stub(:save).and_return(false)
        put :update, {:id => organismo_interno.to_param, :organismo_interno => {}}, valid_session
        assigns(:organismo_interno).should eq(organismo_interno)
      end

      it "re-renders the 'edit' template" do
        organismo_interno = OrganismoInterno.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismoInterno.any_instance.stub(:save).and_return(false)
        put :update, {:id => organismo_interno.to_param, :organismo_interno => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested organismo_interno" do
      organismo_interno = OrganismoInterno.create! valid_attributes
      expect {
        delete :destroy, {:id => organismo_interno.to_param}, valid_session
      }.to change(OrganismoInterno, :count).by(-1)
    end

    it "redirects to the organismos_internos list" do
      organismo_interno = OrganismoInterno.create! valid_attributes
      delete :destroy, {:id => organismo_interno.to_param}, valid_session
      response.should redirect_to(organismos_internos_url)
    end
  end

end
