require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PersonasFisicasController do

  # This should return the minimal set of attributes required to create a valid
  # PersonaFisica. As you add validations to PersonaFisica, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonasFisicasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all personas_fisicas as @personas_fisicas" do
      persona_fisica = PersonaFisica.create! valid_attributes
      get :index, {}, valid_session
      assigns(:personas_fisicas).should eq([persona_fisica])
    end
  end

  describe "GET show" do
    it "assigns the requested persona_fisica as @persona_fisica" do
      persona_fisica = PersonaFisica.create! valid_attributes
      get :show, {:id => persona_fisica.to_param}, valid_session
      assigns(:persona_fisica).should eq(persona_fisica)
    end
  end

  describe "GET new" do
    it "assigns a new persona_fisica as @persona_fisica" do
      get :new, {}, valid_session
      assigns(:persona_fisica).should be_a_new(PersonaFisica)
    end
  end

  describe "GET edit" do
    it "assigns the requested persona_fisica as @persona_fisica" do
      persona_fisica = PersonaFisica.create! valid_attributes
      get :edit, {:id => persona_fisica.to_param}, valid_session
      assigns(:persona_fisica).should eq(persona_fisica)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PersonaFisica" do
        expect {
          post :create, {:persona_fisica => valid_attributes}, valid_session
        }.to change(PersonaFisica, :count).by(1)
      end

      it "assigns a newly created persona_fisica as @persona_fisica" do
        post :create, {:persona_fisica => valid_attributes}, valid_session
        assigns(:persona_fisica).should be_a(PersonaFisica)
        assigns(:persona_fisica).should be_persisted
      end

      it "redirects to the created persona_fisica" do
        post :create, {:persona_fisica => valid_attributes}, valid_session
        response.should redirect_to(PersonaFisica.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved persona_fisica as @persona_fisica" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonaFisica.any_instance.stub(:save).and_return(false)
        post :create, {:persona_fisica => {}}, valid_session
        assigns(:persona_fisica).should be_a_new(PersonaFisica)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonaFisica.any_instance.stub(:save).and_return(false)
        post :create, {:persona_fisica => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested persona_fisica" do
        persona_fisica = PersonaFisica.create! valid_attributes
        # Assuming there are no other personas_fisicas in the database, this
        # specifies that the PersonaFisica created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PersonaFisica.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => persona_fisica.to_param, :persona_fisica => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested persona_fisica as @persona_fisica" do
        persona_fisica = PersonaFisica.create! valid_attributes
        put :update, {:id => persona_fisica.to_param, :persona_fisica => valid_attributes}, valid_session
        assigns(:persona_fisica).should eq(persona_fisica)
      end

      it "redirects to the persona_fisica" do
        persona_fisica = PersonaFisica.create! valid_attributes
        put :update, {:id => persona_fisica.to_param, :persona_fisica => valid_attributes}, valid_session
        response.should redirect_to(persona_fisica)
      end
    end

    describe "with invalid params" do
      it "assigns the persona_fisica as @persona_fisica" do
        persona_fisica = PersonaFisica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonaFisica.any_instance.stub(:save).and_return(false)
        put :update, {:id => persona_fisica.to_param, :persona_fisica => {}}, valid_session
        assigns(:persona_fisica).should eq(persona_fisica)
      end

      it "re-renders the 'edit' template" do
        persona_fisica = PersonaFisica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonaFisica.any_instance.stub(:save).and_return(false)
        put :update, {:id => persona_fisica.to_param, :persona_fisica => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested persona_fisica" do
      persona_fisica = PersonaFisica.create! valid_attributes
      expect {
        delete :destroy, {:id => persona_fisica.to_param}, valid_session
      }.to change(PersonaFisica, :count).by(-1)
    end

    it "redirects to the personas_fisicas list" do
      persona_fisica = PersonaFisica.create! valid_attributes
      delete :destroy, {:id => persona_fisica.to_param}, valid_session
      response.should redirect_to(personas_fisicas_url)
    end
  end

end
