require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubprocesosController do

  # This should return the minimal set of attributes required to create a valid
  # Subproceso. As you add validations to Subproceso, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubprocesosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all subprocesos as @subprocesos" do
      subproceso = Subproceso.create! valid_attributes
      get :index, {}, valid_session
      assigns(:subprocesos).should eq([subproceso])
    end
  end

  describe "GET show" do
    it "assigns the requested subproceso as @subproceso" do
      subproceso = Subproceso.create! valid_attributes
      get :show, {:id => subproceso.to_param}, valid_session
      assigns(:subproceso).should eq(subproceso)
    end
  end

  describe "GET new" do
    it "assigns a new subproceso as @subproceso" do
      get :new, {}, valid_session
      assigns(:subproceso).should be_a_new(Subproceso)
    end
  end

  describe "GET edit" do
    it "assigns the requested subproceso as @subproceso" do
      subproceso = Subproceso.create! valid_attributes
      get :edit, {:id => subproceso.to_param}, valid_session
      assigns(:subproceso).should eq(subproceso)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Subproceso" do
        expect {
          post :create, {:subproceso => valid_attributes}, valid_session
        }.to change(Subproceso, :count).by(1)
      end

      it "assigns a newly created subproceso as @subproceso" do
        post :create, {:subproceso => valid_attributes}, valid_session
        assigns(:subproceso).should be_a(Subproceso)
        assigns(:subproceso).should be_persisted
      end

      it "redirects to the created subproceso" do
        post :create, {:subproceso => valid_attributes}, valid_session
        response.should redirect_to(Subproceso.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subproceso as @subproceso" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subproceso.any_instance.stub(:save).and_return(false)
        post :create, {:subproceso => {}}, valid_session
        assigns(:subproceso).should be_a_new(Subproceso)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subproceso.any_instance.stub(:save).and_return(false)
        post :create, {:subproceso => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subproceso" do
        subproceso = Subproceso.create! valid_attributes
        # Assuming there are no other subprocesos in the database, this
        # specifies that the Subproceso created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Subproceso.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => subproceso.to_param, :subproceso => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested subproceso as @subproceso" do
        subproceso = Subproceso.create! valid_attributes
        put :update, {:id => subproceso.to_param, :subproceso => valid_attributes}, valid_session
        assigns(:subproceso).should eq(subproceso)
      end

      it "redirects to the subproceso" do
        subproceso = Subproceso.create! valid_attributes
        put :update, {:id => subproceso.to_param, :subproceso => valid_attributes}, valid_session
        response.should redirect_to(subproceso)
      end
    end

    describe "with invalid params" do
      it "assigns the subproceso as @subproceso" do
        subproceso = Subproceso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subproceso.any_instance.stub(:save).and_return(false)
        put :update, {:id => subproceso.to_param, :subproceso => {}}, valid_session
        assigns(:subproceso).should eq(subproceso)
      end

      it "re-renders the 'edit' template" do
        subproceso = Subproceso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subproceso.any_instance.stub(:save).and_return(false)
        put :update, {:id => subproceso.to_param, :subproceso => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subproceso" do
      subproceso = Subproceso.create! valid_attributes
      expect {
        delete :destroy, {:id => subproceso.to_param}, valid_session
      }.to change(Subproceso, :count).by(-1)
    end

    it "redirects to the subprocesos list" do
      subproceso = Subproceso.create! valid_attributes
      delete :destroy, {:id => subproceso.to_param}, valid_session
      response.should redirect_to(subprocesos_url)
    end
  end

end
