require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UnidadesTiemposController do

  # This should return the minimal set of attributes required to create a valid
  # UnidadTiempo. As you add validations to UnidadTiempo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UnidadesTiemposController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all unidades_tiempos as @unidades_tiempos" do
      unidad_tiempo = UnidadTiempo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:unidades_tiempos).should eq([unidad_tiempo])
    end
  end

  describe "GET show" do
    it "assigns the requested unidad_tiempo as @unidad_tiempo" do
      unidad_tiempo = UnidadTiempo.create! valid_attributes
      get :show, {:id => unidad_tiempo.to_param}, valid_session
      assigns(:unidad_tiempo).should eq(unidad_tiempo)
    end
  end

  describe "GET new" do
    it "assigns a new unidad_tiempo as @unidad_tiempo" do
      get :new, {}, valid_session
      assigns(:unidad_tiempo).should be_a_new(UnidadTiempo)
    end
  end

  describe "GET edit" do
    it "assigns the requested unidad_tiempo as @unidad_tiempo" do
      unidad_tiempo = UnidadTiempo.create! valid_attributes
      get :edit, {:id => unidad_tiempo.to_param}, valid_session
      assigns(:unidad_tiempo).should eq(unidad_tiempo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UnidadTiempo" do
        expect {
          post :create, {:unidad_tiempo => valid_attributes}, valid_session
        }.to change(UnidadTiempo, :count).by(1)
      end

      it "assigns a newly created unidad_tiempo as @unidad_tiempo" do
        post :create, {:unidad_tiempo => valid_attributes}, valid_session
        assigns(:unidad_tiempo).should be_a(UnidadTiempo)
        assigns(:unidad_tiempo).should be_persisted
      end

      it "redirects to the created unidad_tiempo" do
        post :create, {:unidad_tiempo => valid_attributes}, valid_session
        response.should redirect_to(UnidadTiempo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved unidad_tiempo as @unidad_tiempo" do
        # Trigger the behavior that occurs when invalid params are submitted
        UnidadTiempo.any_instance.stub(:save).and_return(false)
        post :create, {:unidad_tiempo => {}}, valid_session
        assigns(:unidad_tiempo).should be_a_new(UnidadTiempo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UnidadTiempo.any_instance.stub(:save).and_return(false)
        post :create, {:unidad_tiempo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested unidad_tiempo" do
        unidad_tiempo = UnidadTiempo.create! valid_attributes
        # Assuming there are no other unidades_tiempos in the database, this
        # specifies that the UnidadTiempo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UnidadTiempo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => unidad_tiempo.to_param, :unidad_tiempo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested unidad_tiempo as @unidad_tiempo" do
        unidad_tiempo = UnidadTiempo.create! valid_attributes
        put :update, {:id => unidad_tiempo.to_param, :unidad_tiempo => valid_attributes}, valid_session
        assigns(:unidad_tiempo).should eq(unidad_tiempo)
      end

      it "redirects to the unidad_tiempo" do
        unidad_tiempo = UnidadTiempo.create! valid_attributes
        put :update, {:id => unidad_tiempo.to_param, :unidad_tiempo => valid_attributes}, valid_session
        response.should redirect_to(unidad_tiempo)
      end
    end

    describe "with invalid params" do
      it "assigns the unidad_tiempo as @unidad_tiempo" do
        unidad_tiempo = UnidadTiempo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UnidadTiempo.any_instance.stub(:save).and_return(false)
        put :update, {:id => unidad_tiempo.to_param, :unidad_tiempo => {}}, valid_session
        assigns(:unidad_tiempo).should eq(unidad_tiempo)
      end

      it "re-renders the 'edit' template" do
        unidad_tiempo = UnidadTiempo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UnidadTiempo.any_instance.stub(:save).and_return(false)
        put :update, {:id => unidad_tiempo.to_param, :unidad_tiempo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested unidad_tiempo" do
      unidad_tiempo = UnidadTiempo.create! valid_attributes
      expect {
        delete :destroy, {:id => unidad_tiempo.to_param}, valid_session
      }.to change(UnidadTiempo, :count).by(-1)
    end

    it "redirects to the unidades_tiempos list" do
      unidad_tiempo = UnidadTiempo.create! valid_attributes
      delete :destroy, {:id => unidad_tiempo.to_param}, valid_session
      response.should redirect_to(unidades_tiempos_url)
    end
  end

end
